#!/usr/bin/env python3
"""Validate and render the Millennium A/B persistent-state contract."""

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import stat


class PersistentStateError(Exception):
    pass


REQUIRED_TARGETS = frozenset({
    "/etc/machine-id",
    "/etc/ssh/ssh_host_ed25519_key",
    "/etc/ssh/ssh_host_ed25519_key.pub",
    "/etc/ssh/ssh_host_rsa_key",
    "/etc/ssh/ssh_host_rsa_key.pub",
    "/etc/millennium",
    "/etc/NetworkManager/system-connections",
    "/home/millennium/.ssh",
    "/var/lib/millennium",
    "/var/log/millennium",
})

FORBIDDEN_PREFIXES = (
    "/opt/millennium", "/usr", "/boot", "/bin", "/sbin", "/lib",
)


def load(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PersistentStateError("invalid persistent-state JSON") from exc


def _mode(value):
    if not isinstance(value, str) or not re.fullmatch(r"0[0-7]{3}", value):
        raise PersistentStateError("invalid persistent-state mode")
    return int(value, 8)


def validate(value):
    if value.get("schema") != 1 or value.get("state_schema") != 1:
        raise PersistentStateError("unsupported persistent-state schema")
    label = value.get("filesystem_label")
    if not isinstance(label, str) or not re.fullmatch(r"[A-Z0-9_-]{1,16}", label):
        raise PersistentStateError("invalid persistent filesystem label")
    mount = PurePosixPath(value.get("mount_point", ""))
    if str(mount) != value.get("mount_point") or not mount.is_absolute() or mount == PurePosixPath("/"):
        raise PersistentStateError("invalid persistent mount point")
    entries = value.get("entries")
    if not isinstance(entries, list) or not entries:
        raise PersistentStateError("persistent-state entries are missing")
    sources = set()
    targets = set()
    for entry in entries:
        source_text = entry.get("source")
        target_text = entry.get("target")
        if not isinstance(source_text, str) or not isinstance(target_text, str):
            raise PersistentStateError("persistent-state path must be text")
        source = PurePosixPath(source_text)
        target = PurePosixPath(target_text)
        if (source.is_absolute() or ".." in source.parts or str(source) != source_text
                or not target.is_absolute() or str(target) != target_text
                or target == PurePosixPath("/")):
            raise PersistentStateError("unsafe persistent-state path")
        if source_text in sources or target_text in targets:
            raise PersistentStateError("duplicate persistent-state path")
        if any(target_text == prefix or target_text.startswith(prefix + "/")
               for prefix in FORBIDDEN_PREFIXES):
            raise PersistentStateError("replaceable software cannot be persistent")
        kind = entry.get("kind")
        if kind not in ("file", "directory"):
            raise PersistentStateError("invalid persistent-state entry kind")
        mode = _mode(entry.get("mode"))
        if (not isinstance(entry.get("uid"), int) or entry["uid"] < 0
                or not isinstance(entry.get("gid"), int) or entry["gid"] < 0):
            raise PersistentStateError("invalid persistent-state ownership")
        if ("key" in target.name and not target.name.endswith(".pub") and mode & 0o077
                or target_text.endswith("/.ssh") and mode & 0o077
                or target_text.endswith("system-connections") and mode & 0o077):
            raise PersistentStateError("persistent secret permissions are too broad")
        sources.add(source_text)
        targets.add(target_text)
    if targets != REQUIRED_TARGETS:
        missing = sorted(REQUIRED_TARGETS - targets)
        extra = sorted(targets - REQUIRED_TARGETS)
        raise PersistentStateError("persistent target set mismatch; missing=%r extra=%r" %
                                   (missing, extra))
    ordered = sorted(targets)
    for index, first in enumerate(ordered):
        for second in ordered[index + 1:]:
            if second.startswith(first.rstrip("/") + "/"):
                raise PersistentStateError("overlapping persistent targets")
    return value


def render_fstab(value):
    validate(value)
    mount = value["mount_point"]
    lines = [
        "# Generated by persistent_state.py; do not edit.",
        "LABEL=%s %s ext4 defaults,nodev,nosuid 0 2" %
        (value["filesystem_label"], mount),
    ]
    for entry in sorted(value["entries"], key=lambda item: item["target"]):
        lines.append("%s/%s %s none bind,x-systemd.requires-mounts-for=%s 0 0" %
                     (mount, entry["source"], entry["target"], mount))
    return "\n".join(lines) + "\n"


def render_tmpfiles(value):
    validate(value)
    mount = value["mount_point"]
    lines = ["# Generated by persistent_state.py; do not edit."]
    made = set()
    for entry in sorted(value["entries"], key=lambda item: item["source"]):
        source = PurePosixPath(mount) / entry["source"]
        for parent in reversed(source.parents):
            text = str(parent)
            if text.startswith(mount + "/") and text not in made:
                lines.append("d %s 0700 root root -" % text)
                made.add(text)
        if entry["kind"] == "directory" and str(source) not in made:
            lines.append("d %s %s %d %d -" %
                         (source, entry["mode"], entry["uid"], entry["gid"]))
            made.add(str(source))
        target = PurePosixPath(entry["target"])
        if entry["kind"] == "directory":
            lines.append("d %s %s %d %d -" %
                         (target, entry["mode"], entry["uid"], entry["gid"]))
        else:
            lines.append("f %s %s %d %d -" %
                         (target, entry["mode"], entry["uid"], entry["gid"]))
    return "\n".join(lines) + "\n"


def _inside(path, root):
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def validate_source_tree(path):
    path = Path(path)
    if path.is_symlink():
        raise PersistentStateError("top-level persistent source cannot be a symlink")
    for item in [path] + list(path.rglob("*")):
        info = item.lstat()
        if stat.S_ISLNK(info.st_mode):
            target = Path(os.readlink(item))
            resolved = (item.parent / target).resolve() if not target.is_absolute() else target
            if not _inside(resolved, path):
                raise PersistentStateError("persistent source symlink escapes its entry")
        elif not (stat.S_ISREG(info.st_mode) or stat.S_ISDIR(info.st_mode)):
            raise PersistentStateError("persistent source contains a special file")


def tree_digest(path):
    path = Path(path)
    digest = hashlib.sha256()
    items = [path] if path.is_file() else [path] + sorted(path.rglob("*"))
    for item in items:
        relative = "." if item == path else item.relative_to(path).as_posix()
        info = item.lstat()
        digest.update(relative.encode("utf-8") + b"\0")
        digest.update((info.st_mode & 0o7777).to_bytes(2, "big"))
        digest.update(info.st_uid.to_bytes(4, "big"))
        digest.update(info.st_gid.to_bytes(4, "big"))
        if stat.S_ISLNK(info.st_mode):
            digest.update(b"L" + os.readlink(item).encode("utf-8"))
        elif stat.S_ISDIR(info.st_mode):
            digest.update(b"D")
        else:
            digest.update(b"F")
            with item.open("rb") as stream:
                for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(chunk)
    return digest.hexdigest()


def _preserve_tree_ownership(source, destination):
    """Copy numeric ownership without following links in a validated tree."""
    source = Path(source)
    destination = Path(destination)
    source_items = [source] if source.is_file() else [source] + list(source.rglob("*"))
    for source_item in source_items:
        relative = Path() if source_item == source else source_item.relative_to(source)
        destination_item = destination / relative
        info = source_item.lstat()
        os.chown(destination_item, info.st_uid, info.st_gid, follow_symlinks=False)


def _apply_identity(path, entry, ownership):
    os.chmod(path, int(entry["mode"], 8), follow_symlinks=False)
    if ownership:
        os.chown(path, entry["uid"], entry["gid"], follow_symlinks=False)


def seed_persistent_state(value, staging_root, persistent_root,
                          apply_ownership=True):
    validate(value)
    staging_root = Path(staging_root).resolve()
    persistent_root = Path(persistent_root).resolve()
    if not staging_root.is_dir() or not persistent_root.is_dir():
        raise PersistentStateError("staging and persistent roots must exist")
    existing = {item.name for item in persistent_root.iterdir()}
    if existing - {"lost+found"}:
        raise PersistentStateError("persistent destination is not empty")
    if apply_ownership and os.geteuid() != 0:
        raise PersistentStateError("root is required to preserve persistent ownership")
    inventory = []
    for entry in sorted(value["entries"], key=lambda item: item["target"]):
        source = staging_root / entry["target"].lstrip("/")
        destination = persistent_root / entry["source"]
        if not source.exists():
            raise PersistentStateError("missing staged persistent source: %s" %
                                       entry["target"])
        if ((entry["kind"] == "file") != source.is_file()
                or (entry["kind"] == "directory") != source.is_dir()):
            raise PersistentStateError("staged persistent source kind mismatch")
        validate_source_tree(source)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists() or destination.is_symlink():
            raise PersistentStateError("persistent destination collision")
        if entry["kind"] == "directory":
            shutil.copytree(source, destination, symlinks=True)
        else:
            shutil.copy2(source, destination, follow_symlinks=False)
        if apply_ownership:
            _preserve_tree_ownership(source, destination)
        _apply_identity(destination, entry, apply_ownership)
        inventory.append({
            "source": entry["source"], "target": entry["target"],
            "kind": entry["kind"], "mode": entry["mode"],
            "uid": entry["uid"], "gid": entry["gid"],
            "sha256": tree_digest(destination),
        })
    record = {
        "schema": 1, "operation": "persistent-state-seed",
        "state_schema": value["state_schema"],
        "filesystem_label": value["filesystem_label"],
        "entries": inventory,
    }
    record_path = persistent_root / ".millennium-state.json"
    record_path.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n",
                           encoding="utf-8")
    os.chmod(record_path, 0o600)
    return record


def verify_persistent_state(value, persistent_root, check_ownership=True):
    validate(value)
    persistent_root = Path(persistent_root).resolve()
    try:
        record = json.loads((persistent_root / ".millennium-state.json").read_text(
            encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PersistentStateError("persistent-state inventory is missing or invalid") from exc
    expected_entries = {entry["source"]: entry for entry in value["entries"]}
    recorded = {entry.get("source"): entry for entry in record.get("entries", [])}
    if (record.get("schema") != 1 or record.get("operation") != "persistent-state-seed"
            or record.get("state_schema") != value["state_schema"]
            or record.get("filesystem_label") != value["filesystem_label"]
            or len(record.get("entries", [])) != len(expected_entries)
            or set(recorded) != set(expected_entries)):
        raise PersistentStateError("persistent-state inventory does not match contract")
    for source, entry in expected_entries.items():
        path = persistent_root / source
        if not path.exists() or path.is_symlink():
            raise PersistentStateError("persistent entry is missing")
        info = path.stat()
        if ((entry["kind"] == "file") != path.is_file()
                or (entry["kind"] == "directory") != path.is_dir()
                or stat.S_IMODE(info.st_mode) != int(entry["mode"], 8)):
            raise PersistentStateError("persistent entry kind or mode changed")
        if check_ownership and (info.st_uid != entry["uid"] or info.st_gid != entry["gid"]):
            raise PersistentStateError("persistent entry ownership changed")
        if tree_digest(path) != recorded[source].get("sha256"):
            raise PersistentStateError("persistent entry content changed since staging")
    return record


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("contract", type=Path)
    parser.add_argument("--fstab", type=Path)
    parser.add_argument("--tmpfiles", type=Path)
    parser.add_argument("--seed-from", type=Path)
    parser.add_argument("--persistent-root", type=Path)
    parser.add_argument("--verify-root", type=Path)
    args = parser.parse_args()
    value = validate(load(args.contract))
    if args.fstab:
        args.fstab.write_text(render_fstab(value), encoding="utf-8")
    if args.tmpfiles:
        args.tmpfiles.write_text(render_tmpfiles(value), encoding="utf-8")
    if bool(args.seed_from) != bool(args.persistent_root):
        parser.error("--seed-from and --persistent-root must be used together")
    if args.seed_from:
        seed_persistent_state(value, args.seed_from, args.persistent_root)
        print("SEEDED: persistent-state contract %d" % value["state_schema"])
    if args.verify_root:
        verify_persistent_state(value, args.verify_root)
        print("VERIFIED: persistent-state contract %d" % value["state_schema"])
    if not any((args.fstab, args.tmpfiles, args.seed_from, args.verify_root)):
        print("VALID: persistent-state contract %d" % value["state_schema"])


if __name__ == "__main__":
    main()
