#!/usr/bin/env python3
"""Validate and render the Millennium A/B persistent-state contract."""

import argparse
import json
from pathlib import Path, PurePosixPath
import re


class PersistentStateError(Exception):
    pass


REQUIRED_TARGETS = frozenset({
    "/etc/machine-id",
    "/etc/ssh/ssh_host_ed25519_key",
    "/etc/ssh/ssh_host_ed25519_key.pub",
    "/etc/ssh/ssh_host_rsa_key",
    "/etc/ssh/ssh_host_rsa_key.pub",
    "/etc/millennium",
    "/etc/NetworkManager/system-connections",
    "/home/matzen/.ssh",
    "/var/lib/millennium",
    "/var/log/millennium",
})

FORBIDDEN_PREFIXES = (
    "/opt/millennium", "/usr", "/boot", "/bin", "/sbin", "/lib",
)


def load(path):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PersistentStateError("invalid persistent-state JSON") from exc


def _mode(value):
    if not isinstance(value, str) or not re.fullmatch(r"0[0-7]{3}", value):
        raise PersistentStateError("invalid persistent-state mode")
    return int(value, 8)


def validate(value):
    if value.get("schema") != 1 or value.get("state_schema") != 1:
        raise PersistentStateError("unsupported persistent-state schema")
    label = value.get("filesystem_label")
    if not isinstance(label, str) or not re.fullmatch(r"[A-Z0-9_-]{1,16}", label):
        raise PersistentStateError("invalid persistent filesystem label")
    mount = PurePosixPath(value.get("mount_point", ""))
    if str(mount) != value.get("mount_point") or not mount.is_absolute() or mount == PurePosixPath("/"):
        raise PersistentStateError("invalid persistent mount point")
    entries = value.get("entries")
    if not isinstance(entries, list) or not entries:
        raise PersistentStateError("persistent-state entries are missing")
    sources = set()
    targets = set()
    for entry in entries:
        source_text = entry.get("source")
        target_text = entry.get("target")
        if not isinstance(source_text, str) or not isinstance(target_text, str):
            raise PersistentStateError("persistent-state path must be text")
        source = PurePosixPath(source_text)
        target = PurePosixPath(target_text)
        if (source.is_absolute() or ".." in source.parts or str(source) != source_text
                or not target.is_absolute() or str(target) != target_text
                or target == PurePosixPath("/")):
            raise PersistentStateError("unsafe persistent-state path")
        if source_text in sources or target_text in targets:
            raise PersistentStateError("duplicate persistent-state path")
        if any(target_text == prefix or target_text.startswith(prefix + "/")
               for prefix in FORBIDDEN_PREFIXES):
            raise PersistentStateError("replaceable software cannot be persistent")
        kind = entry.get("kind")
        if kind not in ("file", "directory"):
            raise PersistentStateError("invalid persistent-state entry kind")
        mode = _mode(entry.get("mode"))
        if (not isinstance(entry.get("uid"), int) or entry["uid"] < 0
                or not isinstance(entry.get("gid"), int) or entry["gid"] < 0):
            raise PersistentStateError("invalid persistent-state ownership")
        if ("key" in target.name and not target.name.endswith(".pub") and mode & 0o077
                or target_text.endswith("/.ssh") and mode & 0o077
                or target_text.endswith("system-connections") and mode & 0o077):
            raise PersistentStateError("persistent secret permissions are too broad")
        sources.add(source_text)
        targets.add(target_text)
    if targets != REQUIRED_TARGETS:
        missing = sorted(REQUIRED_TARGETS - targets)
        extra = sorted(targets - REQUIRED_TARGETS)
        raise PersistentStateError("persistent target set mismatch; missing=%r extra=%r" %
                                   (missing, extra))
    ordered = sorted(targets)
    for index, first in enumerate(ordered):
        for second in ordered[index + 1:]:
            if second.startswith(first.rstrip("/") + "/"):
                raise PersistentStateError("overlapping persistent targets")
    return value


def render_fstab(value):
    validate(value)
    mount = value["mount_point"]
    lines = [
        "# Generated by persistent_state.py; do not edit.",
        "LABEL=%s %s ext4 defaults,nodev,nosuid 0 2" %
        (value["filesystem_label"], mount),
    ]
    for entry in sorted(value["entries"], key=lambda item: item["target"]):
        lines.append("%s/%s %s none bind,x-systemd.requires-mounts-for=%s 0 0" %
                     (mount, entry["source"], entry["target"], mount))
    return "\n".join(lines) + "\n"


def render_tmpfiles(value):
    validate(value)
    mount = value["mount_point"]
    lines = ["# Generated by persistent_state.py; do not edit."]
    made = set()
    for entry in sorted(value["entries"], key=lambda item: item["source"]):
        source = PurePosixPath(mount) / entry["source"]
        for parent in reversed(source.parents):
            text = str(parent)
            if text.startswith(mount + "/") and text not in made:
                lines.append("d %s 0700 root root -" % text)
                made.add(text)
        if entry["kind"] == "directory" and str(source) not in made:
            lines.append("d %s %s %d %d -" %
                         (source, entry["mode"], entry["uid"], entry["gid"]))
            made.add(str(source))
        target = PurePosixPath(entry["target"])
        if entry["kind"] == "directory":
            lines.append("d %s %s %d %d -" %
                         (target, entry["mode"], entry["uid"], entry["gid"]))
        else:
            lines.append("f %s %s %d %d -" %
                         (target, entry["mode"], entry["uid"], entry["gid"]))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("contract", type=Path)
    parser.add_argument("--fstab", type=Path)
    parser.add_argument("--tmpfiles", type=Path)
    args = parser.parse_args()
    value = validate(load(args.contract))
    if args.fstab:
        args.fstab.write_text(render_fstab(value), encoding="utf-8")
    if args.tmpfiles:
        args.tmpfiles.write_text(render_tmpfiles(value), encoding="utf-8")
    if not args.fstab and not args.tmpfiles:
        print("VALID: persistent-state contract %d" % value["state_schema"])


if __name__ == "__main__":
    main()
