M48
; DRILL file {KiCad 7.0.9} date Monday, January 29, 2024 at 07:46:45 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T19:46:45-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1083
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1280
%
G90
G05
T1
X6.4Y-0.9
X6.4Y-2.1
T2
X7.3945Y-4.1441
X7.3945Y-4.3803
X7.6945Y-4.1425
X7.6945Y-4.3787
T3
X4.6Y-0.9
X4.6Y-1.5
X4.6Y-2.1
X4.6Y-2.7
X6.4Y-1.5
X6.4Y-2.7
T4
X6.7Y-1.0
X6.7Y-3.2835
X7.6055Y-1.0
X7.6055Y-3.2835
T5
X6.7992Y-4.2925
T6
X7.0945Y-4.2925
T0
M30
