#!/usr/bin/env python3
"""Generate checked-in compatibility documentation from authoritative sources."""

import argparse
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]


def metadata():
    version = (ROOT / "VERSION").read_text().strip()
    protocol_header = (ROOT / "Arduino/libraries/MillenniumProtocol/src/"
                       "MillenniumProtocol.h").read_text()
    match = re.search(r"^#define MILLENNIUM_PROTOCOL_VERSION ([0-9]+)$",
                      protocol_header, re.MULTILINE)
    if not match:
        raise SystemExit("firmware protocol definition is missing")
    return {"software_version": version, "ota_manifest_schema": 1,
            "ota_release_schema": 1, "mcu_protocol": int(match.group(1)),
            "story_source_schema": 1, "story_runtime_schema": 1,
            "content_manifest_schema": 1}


def outputs(data):
    rendered_json = json.dumps(data, indent=2, sort_keys=True) + "\n"
    rendered_markdown = f"""# Generated compatibility metadata

Do not edit this file directly. Run `python3 tools/generate_version_metadata.py`.

| Component | Current value |
| --- | ---: |
| Host and MCU software | `{data['software_version']}` |
| OTA manifest schema | `{data['ota_manifest_schema']}` |
| OTA release schema | `{data['ota_release_schema']}` |
| MCU serial protocol | `{data['mcu_protocol']}` |
| Story source schema | `{data['story_source_schema']}` |
| Story runtime schema | `{data['story_runtime_schema']}` |
| Content manifest schema | `{data['content_manifest_schema']}` |

The host release and both MCU roles must report the same software version.
Protocol or schema changes require an explicit compatibility migration; they
must never be inferred from the marketing version alone.
"""
    return {ROOT / "docs/VERSION.json": rendered_json,
            ROOT / "docs/COMPATIBILITY.md": rendered_markdown}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, text in outputs(metadata()).items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(path.relative_to(ROOT))
    if stale:
        print("stale generated version metadata: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
